# Generated by Django 6.0.6 on 2026-06-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('nit', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('moneda', models.TextField(default='COP')),
                ('porcentaje_impuesto', models.FloatField(default=0)),
                ('activa', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.TextField(default='DISPONIBLE')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RenovacionLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateTimeField(auto_now_add=True)),
                ('meses_agregados', models.IntegerField()),
                ('nueva_fecha_vencimiento', models.DateTimeField()),
                ('monto_pagado', models.FloatField(default=0)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='empresas.licenciatoken')),
            ],
        ),
    ]
