# Generated by Django 6.0.6 on 2026-07-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_eventoempresa'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='empresa',
                    table='empresa',
                ),
                migrations.AlterModelTable(
                    name='licenciatoken',
                    table='licencia_token',
                ),
                migrations.AlterModelTable(
                    name='renovacionlicencia',
                    table='renovacion_licencia',
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='empresa',
                    table='empresa',
                ),
                migrations.AlterModelTable(
                    name='licenciatoken',
                    table='licencia_token',
                ),
                migrations.AlterModelTable(
                    name='renovacionlicencia',
                    table='renovacion_licencia',
                ),
            ],
        ),
    ]
