# Generated by Django 6.0.6 on 2026-07-10 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_fix_evento_empresa_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='renovacionlicencia',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
