# Generated by Django 6.0.6 on 2026-07-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_empresa_alter_usuario_rol_and_more'),
        ('ventas', '0002_venta_cliente_pago_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='usuarios.sucursal'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='abono',
                    table='abono',
                ),
                migrations.AlterModelTable(
                    name='auditoriadescuento',
                    table='auditoria_descuento',
                ),
                migrations.AlterModelTable(
                    name='compra',
                    table='compra',
                ),
                migrations.AlterModelTable(
                    name='itemcompra',
                    table='item_compra',
                ),
                migrations.AlterModelTable(
                    name='itemventa',
                    table='item_venta',
                ),
                migrations.AlterModelTable(
                    name='kardex',
                    table='kardex',
                ),
                migrations.AlterModelTable(
                    name='logactividad',
                    table='log_actividad',
                ),
                migrations.AlterModelTable(
                    name='movimientocaja',
                    table='movimiento_caja',
                ),
                migrations.AlterModelTable(
                    name='pagoproveedor',
                    table='pago_proveedor',
                ),
                migrations.AlterModelTable(
                    name='secuencias',
                    table='secuencias',
                ),
                migrations.AlterModelTable(
                    name='venta',
                    table='venta',
                ),
            ],
        ),
    ]
