# Generated by Django 6.0.6 on 2026-07-10 19:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_compra_sucursal_alter_abono_table_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS trg_venta_after_insert_credito ON venta;
            DROP TRIGGER IF EXISTS trg_abono_after_insert ON abono;
            DROP TRIGGER IF EXISTS trg_pago_proveedor_after_insert ON pago_proveedor;
            """,
            reverse_sql="""
            CREATE TRIGGER trg_venta_after_insert_credito
            AFTER INSERT ON venta
            FOR EACH ROW
            WHEN (NEW.saldo_pendiente > 0)
            EXECUTE FUNCTION fn_trg_venta_credito();

            CREATE TRIGGER trg_abono_after_insert
            AFTER INSERT ON abono
            FOR EACH ROW EXECUTE FUNCTION fn_trg_abono();

            CREATE TRIGGER trg_pago_proveedor_after_insert
            AFTER INSERT ON pago_proveedor
            FOR EACH ROW EXECUTE FUNCTION fn_trg_pago_proveedor();
            """,
        ),
        migrations.AlterField(
            model_name='abono',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='auditoriadescuento',
            name='descuento_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='auditoriadescuento',
            name='descuento_nuevo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemventa',
            name='utilidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='stock_resultante',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagoproveedor',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='venta',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal_con_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='utilidad_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='venta',
            name='valor_impuesto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER trg_venta_after_insert_credito
            AFTER INSERT ON venta
            FOR EACH ROW
            WHEN (NEW.saldo_pendiente > 0)
            EXECUTE FUNCTION fn_trg_venta_credito();

            CREATE TRIGGER trg_abono_after_insert
            AFTER INSERT ON abono
            FOR EACH ROW EXECUTE FUNCTION fn_trg_abono();

            CREATE TRIGGER trg_pago_proveedor_after_insert
            AFTER INSERT ON pago_proveedor
            FOR EACH ROW EXECUTE FUNCTION fn_trg_pago_proveedor();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_venta_after_insert_credito ON venta;
            DROP TRIGGER IF EXISTS trg_abono_after_insert ON abono;
            DROP TRIGGER IF EXISTS trg_pago_proveedor_after_insert ON pago_proveedor;
            """,
        ),
    ]
