# Generated by Django 6.0.6 on 2026-07-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_table_alter_licenciatoken_table_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='usuario',
                    name='empresa',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='empresas.empresa'),
                ),
                migrations.AlterField(
                    model_name='usuario',
                    name='rol',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='usuarios.rol'),
                ),
                migrations.AlterField(
                    model_name='usuario',
                    name='sucursal',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.sucursal'),
                ),
                migrations.AlterModelTable(
                    name='rol',
                    table='rol',
                ),
                migrations.AlterModelTable(
                    name='sucursal',
                    table='sucursal',
                ),
                migrations.AlterModelTable(
                    name='usuario',
                    table='usuario',
                ),
            ],
        ),
    ]
