# Generated by Django 6.0.6 on 2026-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_empresa_alter_usuario_rol_and_more'),
    ]

    operations = [
        # --- INICIO DE LA CORRECCIÓN MANUAL (Conversión Integer a Boolean) ---
        migrations.RunSQL('ALTER TABLE sucursal ALTER COLUMN activa DROP DEFAULT;'),
        migrations.RunSQL('ALTER TABLE usuario ALTER COLUMN activo DROP DEFAULT;'),
        migrations.RunSQL('ALTER TABLE sucursal ALTER COLUMN activa TYPE boolean USING (activa=1);'),
        migrations.RunSQL('ALTER TABLE usuario ALTER COLUMN activo TYPE boolean USING (activo=1);'),
        # --- FIN DE LA CORRECCIÓN MANUAL ---

        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]