# Generated by Django 6.0.6 on 2026-07-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='caja',
                    table='caja',
                ),
                migrations.AlterModelTable(
                    name='categoria',
                    table='categoria',
                ),
                migrations.AlterModelTable(
                    name='cliente',
                    table='cliente',
                ),
                migrations.AlterModelTable(
                    name='producto',
                    table='producto',
                ),
                migrations.AlterModelTable(
                    name='proveedor',
                    table='proveedor',
                ),
                migrations.AlterModelTable(
                    name='tipocliente',
                    table='tipo_cliente',
                ),
            ],
        ),
    ]
