# Generated by Django 6.0.6 on 2026-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_caja_table_alter_categoria_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(default=0),
        ),
    ]
